### ISSUE TITLE
Azure.json full automation

### ISSUE THREAD

**Issue by iknowjason** [iknowjason/edge#10]
Right now downloading the azure.json is not fully automated.  The url  changes and needs to be manually updated.

Find a method to  do full automation.

**Comment by Azathothas** [comment]
@iknowjason 
One way to do this could be achieved using https://github.com/ivan-sincek/metagoofeel and setting up a GitHub actions to run every time azure.json is updated

**Comment by iknowjason** [comment]
@Azathothas 

Very interesting.  I've been looking for something like this.  Are you aware of an example of how to run ```metagoofeel``` to know when ```azure.json``` is updated?

**Comment by Azathothas** [comment]
@iknowjason 
Actually, there's no need for metagoofeel, as Microsoft, fortunately, doesn't use captchas, etc.
A simple curl one-liner can do it:
Assuming, we only care about , [**Public cloud ranges**(ServiceTags_Public)](https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519) the id is always **`56519`**
[**US_Gov**(ServiceTags_AzureGovernment):**`57063`**](https://www.microsoft.com/en-us/download/confirmation.aspx?id=57063) [**Germany**(ServiceTags_AzureGermany):**`57064`**](https://www.microsoft.com/en-us/download/confirmation.aspx?id=57064) [**China**(ServiceTags_China):**`57062`**](https://www.microsoft.com/en-us/download/confirmation.aspx?id=57062)
```bash
curl -qsk $(curl -qsk "https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519" | grep -o 'href="https://download.microsoft.com/download/.*ServiceTags_Public.*\.json"' | sed 's/href="//' | sed 's/"$//') -o azure.json
!# To suppress output, as the JSON body is huge, simply redirect everything to /dev/null:
curl -qsk $(curl -qsk "https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519" | grep -o 'href="https://download.microsoft.com/download/.*ServiceTags_Public.*\.json"' | sed 's/href="//' | sed 's/"$//') -o azure.json  > /dev/null 2>&1
```

As 
>to know when Azure.json is updated?

A simple guess would be weekly, at least for **ServiceTags_Public**. 
The most recent one has the filename: `ServiceTags_Public_20230501.json`, so **`2023-05-01`**, that's `Monday`, so we can probably set up our workflow cron to do this every Tuesday of every week. 


and an example workflow.yml could look something like:
```yml
name: Update Azure JSON

on:
  schedule:
    - cron: "0 0 * * 2"
  workflow_dispatch:

jobs:
  update-azure-json:
    runs-on: ubuntu-latest
    steps:
      - name: Download Azure JSON
        run: |
          curl -qsk $(curl -qsk "https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519" | grep -o 'href="https://download.microsoft.com/download/.*ServiceTags_Public.*\.json"' | sed 's/href="//' | sed 's/"$//') -o azure.json > /dev/null 2>&1
      
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      
      # Setup Git    
      - name: Set up Git environment
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add azure.json
          git commit -m "Update azure.json"
          git push origin main
      # Commit and push changes
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update azure.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
